### ISSUE TITLE
Forms

### ISSUE THREAD

**Issue by ElgersNiels** [mathijsdelabie/SWOPProject#10]
We kunnen nadenken over hoe we forms gaan verbergen voor de gebruiker.

Is uiteindelijk geen dik drama als het niet lukt, denk ik.

**Comment by MadMatt25** [comment]
Da ga lastig worden eh, want ge moet die aan de gebruiker geven ;) of ge bedoelt enkel de constructors?
In elk geval, door da ze in een andere package zitten zal da idd lastig zijn :/
